### ISSUE TITLE
include paxtest

### ISSUE THREAD

**Issue by ghost** [freedomofpress/ansible-role-grsecurity#47]
I would find it useful to include paxtest into this task:

```
- name: Install PaX utilities.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - paxctl
    - paxtest
```

The main purpose of me wanting this is for post install testing. It may also be valuable to have a second list of tests in tests.yml for:
- a single run post install paxtest tests or reports.
- a recurring job for daily or weekly checking.
- signed kernel checks.

with notifications on any changes. Otherwise I will probably get around to adding these additional checks to my own playbook eventually and can offer a pull request when ready.
